<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
<!-- SKAuto.Import.csproj -->
<ItemGroup>
  <PackageReference Include="ClosedXML" Version="0.102.1" />
  <PackageReference Include="itext7" Version="8.0.1" />
  <ProjectReference Include="..\SKAuto.Core\SKAuto.Core.csproj" />
</ItemGroup>
</Project>
